/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.main;

import com.app.entity.PageResult;
import com.app.services.ProductService;
import com.app.tablemodel.AppTableModel;

/**
 *
 * @author Farmaku
 */
public class PanelUser extends javax.swing.JPanel {
    private ProductService service;
    private PageResult<ProductService> pageResult;
    private AppTableModel <ProductService> tableModel;
    private int page = 1;
    private int pageSize = 10;
    private String[] columnNames = {"User ID", "Name", "Title",
        "Birth Date", "Hire Date", "Position", "Email"};

    /**
     * Creates new form PanelHome
     */
    public PanelUser() {
        initComponents();
    }
    
    private void loadData(){
        try {
            String search = textSearch1.getText();
            String sort = ddlSort.getSelectedItem().toString().replace(" ", "");
            pageResult = service.getPage(search, page, pageSize, sort, ascending1.isSelected());
            tableModel = new AppTableModel<>(pageResult.getContent(),columnNames);
            tableUser.setModel(tableModel);
            
            labelTotalRow1.setText(pageResult.getTotalElements()+"");
            labelPerPage2.setText(String.format("page %d / %d", page, pageResult.getTotalPages()));
            buttonPrev1.setEnabled(!pageResult.isFirst());
            buttonNext1.setEnabled(!pageResult.isLast());
        } catch (Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelSort1 = new javax.swing.JLabel();
        ddlSort = new javax.swing.JComboBox<>();
        textSearch1 = new com.app.components.TextSearch();
        buttonSearch1 = new javax.swing.JButton();
        labelDirection1 = new javax.swing.JLabel();
        ascending1 = new javax.swing.JRadioButton();
        descending1 = new javax.swing.JRadioButton();
        labelTotal1 = new javax.swing.JLabel();
        labelTotalRow1 = new javax.swing.JLabel();
        labelRow1 = new javax.swing.JLabel();
        labelPerPage1 = new javax.swing.JLabel();
        ddlPerPage = new javax.swing.JComboBox<>();
        labelPerPage2 = new javax.swing.JLabel();
        buttonPrev1 = new javax.swing.JButton();
        buttonNext1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daftar User");

        labelSort1.setText("Sort By :");

        ddlSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User ID", "Name", "Title", "Birth Date", "Hire Date", "Position", "Email", " " }));
        ddlSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlSortActionPerformed(evt);
            }
        });

        buttonSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/icons/icons8_search_24px.png"))); // NOI18N
        buttonSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearch1ActionPerformed(evt);
            }
        });

        labelDirection1.setText("Direction");

        ascending1.setBackground(new java.awt.Color(255, 255, 255));
        ascending1.setText("Ascending");
        ascending1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascending1ActionPerformed(evt);
            }
        });

        descending1.setBackground(new java.awt.Color(255, 255, 255));
        descending1.setText("Descending");
        descending1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descending1ActionPerformed(evt);
            }
        });

        labelTotal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTotal1.setText("Total Row:");

        labelTotalRow1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTotalRow1.setText("0");

        labelRow1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelRow1.setText("Row(s)");

        labelPerPage1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPerPage1.setText("Per Page :");

        ddlPerPage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "25", "50", "100" }));
        ddlPerPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlPerPageActionPerformed(evt);
            }
        });

        labelPerPage2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPerPage2.setText("Page 1/10");

        buttonPrev1.setText("Prev");
        buttonPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrev1ActionPerformed(evt);
            }
        });

        buttonNext1.setText("Next");
        buttonNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNext1ActionPerformed(evt);
            }
        });

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Name", "Title", "Birth Date", "Hire Date", "Position", "Email"
            }
        ));
        jScrollPane2.setViewportView(tableUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSort1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ddlSort, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDirection1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ascending1)
                                .addGap(10, 10, 10)
                                .addComponent(descending1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(buttonSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTotalRow1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPerPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ddlPerPage, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPerPage2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonPrev1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNext1)
                        .addGap(11, 11, 11))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSort1)
                    .addComponent(ddlSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDirection1)
                    .addComponent(ascending1)
                    .addComponent(descending1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal1)
                    .addComponent(labelTotalRow1)
                    .addComponent(labelRow1)
                    .addComponent(labelPerPage1)
                    .addComponent(ddlPerPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPerPage2)
                    .addComponent(buttonPrev1)
                    .addComponent(buttonNext1))
                .addGap(687, 687, 687))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ddlSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlSortActionPerformed
        loadData();
    }//GEN-LAST:event_ddlSortActionPerformed

    private void buttonSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearch1ActionPerformed
        loadData();
    }//GEN-LAST:event_buttonSearch1ActionPerformed

    private void ascending1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascending1ActionPerformed
        loadData();
    }//GEN-LAST:event_ascending1ActionPerformed

    private void descending1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descending1ActionPerformed
        loadData();
    }//GEN-LAST:event_descending1ActionPerformed

    private void ddlPerPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlPerPageActionPerformed
        Integer pageSize = Integer.valueOf(ddlPerPage.getSelectedItem().toString());
        page = 1;
        loadData();
    }//GEN-LAST:event_ddlPerPageActionPerformed

    private void buttonPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrev1ActionPerformed
        page--;
        loadData();
    }//GEN-LAST:event_buttonPrev1ActionPerformed

    private void buttonNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNext1ActionPerformed
        page++;
        loadData();
    }//GEN-LAST:event_buttonNext1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ascending1;
    private javax.swing.JButton buttonNext1;
    private javax.swing.JButton buttonPrev1;
    private javax.swing.JButton buttonSearch1;
    private javax.swing.JComboBox<String> ddlPerPage;
    private javax.swing.JComboBox<String> ddlSort;
    private javax.swing.JRadioButton descending1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDirection1;
    private javax.swing.JLabel labelPerPage1;
    private javax.swing.JLabel labelPerPage2;
    private javax.swing.JLabel labelRow1;
    private javax.swing.JLabel labelSort1;
    private javax.swing.JLabel labelTotal1;
    private javax.swing.JLabel labelTotalRow1;
    private javax.swing.JTable tableUser;
    private com.app.components.TextSearch textSearch1;
    // End of variables declaration//GEN-END:variables

}
